/*
 * User Account Management
 * API interface to enroll users and accounts
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Loyalty_Technology_Solutions_Scrum_Vulcans@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.developer.mastercard_loyalty_enrollment_client.api;

import com.mastercard.developer.mastercard_loyalty_enrollment_client.ApiException;
import com.mastercard.developer.mastercard_loyalty_enrollment_client.model.AccountEnrollRequest;
import com.mastercard.developer.mastercard_loyalty_enrollment_client.model.AccountResponse;
import com.mastercard.developer.mastercard_loyalty_enrollment_client.model.AccountSearchRequest;
import com.mastercard.developer.mastercard_loyalty_enrollment_client.model.AccountSearchResponse;
import com.mastercard.developer.mastercard_loyalty_enrollment_client.model.AccountUpdateRequest;
import com.mastercard.developer.mastercard_loyalty_enrollment_client.model.Errors;
import com.mastercard.developer.mastercard_loyalty_enrollment_client.model.PagedResponseAccountSearchResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AccountApi
 */
@Ignore
public class AccountApiTest {

    private final AccountApi api = new AccountApi();

    
    /**
     * Enrolls a new account of an user for a company
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void enrollAccountTest() throws ApiException {
        AccountEnrollRequest accountEnrollRequest = null;
        AccountResponse response = api.enrollAccount(accountEnrollRequest);

        // TODO: test validations
    }
    
    /**
     * Returns the account information for an account of a company
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findAccountTest() throws ApiException {
        String referenceId = null;
        AccountSearchResponse response = api.findAccount(referenceId);

        // TODO: test validations
    }
    
    /**
     * Returns the account information for a company
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void searchAccountTest() throws ApiException {
        AccountSearchRequest accountSearchRequest = null;
        Integer limit = null;
        Integer offset = null;
        PagedResponseAccountSearchResponse response = api.searchAccount(accountSearchRequest, limit, offset);

        // TODO: test validations
    }
    
    /**
     * Updates the status for an account of the company
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateAccountTest() throws ApiException {
        String referenceId = null;
        AccountUpdateRequest accountUpdateRequest = null;
        AccountResponse response = api.updateAccount(referenceId, accountUpdateRequest);

        // TODO: test validations
    }
    
}
