/*
 * User Account Management
 * API interface to enroll users and accounts
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Loyalty_Technology_Solutions_Scrum_Vulcans@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.developer.mastercard_loyalty_enrollment_client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Account
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-02-11T17:56:47.857+05:30[Asia/Kolkata]")
public class Account {
  public static final String SERIALIZED_NAME_ACCOUNT_ID_TYPE = "accountIdType";
  @SerializedName(SERIALIZED_NAME_ACCOUNT_ID_TYPE)
  private String accountIdType;

  public static final String SERIALIZED_NAME_ACCOUNT_ID = "accountId";
  @SerializedName(SERIALIZED_NAME_ACCOUNT_ID)
  private String accountId;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private String status;

  public static final String SERIALIZED_NAME_PRODUCT_CODE = "productCode";
  @SerializedName(SERIALIZED_NAME_PRODUCT_CODE)
  private String productCode;

  public static final String SERIALIZED_NAME_PROGRAM_IDENTIFIER = "programIdentifier";
  @SerializedName(SERIALIZED_NAME_PROGRAM_IDENTIFIER)
  private String programIdentifier;

  public static final String SERIALIZED_NAME_OPEN_DATE = "openDate";
  @SerializedName(SERIALIZED_NAME_OPEN_DATE)
  private String openDate;

  public static final String SERIALIZED_NAME_ENROLLMENT_DATE = "enrollmentDate";
  @SerializedName(SERIALIZED_NAME_ENROLLMENT_DATE)
  private String enrollmentDate;


  public Account accountIdType(String accountIdType) {
    
    this.accountIdType = accountIdType;
    return this;
  }

   /**
   * For real card number enrollment, AccountIdType has to be ACCOUNT_NUMBER
   * @return accountIdType
  **/
  @ApiModelProperty(example = "ACCOUNT_NUMBER", required = true, value = "For real card number enrollment, AccountIdType has to be ACCOUNT_NUMBER")

  public String getAccountIdType() {
    return accountIdType;
  }


  public void setAccountIdType(String accountIdType) {
    this.accountIdType = accountIdType;
  }


  public Account accountId(String accountId) {
    
    this.accountId = accountId;
    return this;
  }

   /**
   * The unique identifier assigned by the Company to an account
   * @return accountId
  **/
  @ApiModelProperty(example = "5330333671236516", required = true, value = "The unique identifier assigned by the Company to an account")

  public String getAccountId() {
    return accountId;
  }


  public void setAccountId(String accountId) {
    this.accountId = accountId;
  }


  public Account status(String status) {
    
    this.status = status;
    return this;
  }

   /**
   * Status for the user&#39;s account; Expected values are - NEW, GOOD_STANDING, REDEEM_ONLY, CANCELLED, ON_HOLD, INACTIVE
   * @return status
  **/
  @ApiModelProperty(example = "NEW", required = true, value = "Status for the user's account; Expected values are - NEW, GOOD_STANDING, REDEEM_ONLY, CANCELLED, ON_HOLD, INACTIVE")

  public String getStatus() {
    return status;
  }


  public void setStatus(String status) {
    this.status = status;
  }


  public Account productCode(String productCode) {
    
    this.productCode = productCode;
    return this;
  }

   /**
   * Card product assigned by the Company
   * @return productCode
  **/
  @ApiModelProperty(example = "7274VCC", required = true, value = "Card product assigned by the Company")

  public String getProductCode() {
    return productCode;
  }


  public void setProductCode(String productCode) {
    this.productCode = productCode;
  }


  public Account programIdentifier(String programIdentifier) {
    
    this.programIdentifier = programIdentifier;
    return this;
  }

   /**
   * Program unique identifier assigned by the Company
   * @return programIdentifier
  **/
  @ApiModelProperty(example = "ZXSzM", required = true, value = "Program unique identifier assigned by the Company")

  public String getProgramIdentifier() {
    return programIdentifier;
  }


  public void setProgramIdentifier(String programIdentifier) {
    this.programIdentifier = programIdentifier;
  }


  public Account openDate(String openDate) {
    
    this.openDate = openDate;
    return this;
  }

   /**
   * The Date when account opened by the Company
   * @return openDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2015-01-01", value = "The Date when account opened by the Company")

  public String getOpenDate() {
    return openDate;
  }


  public void setOpenDate(String openDate) {
    this.openDate = openDate;
  }


  public Account enrollmentDate(String enrollmentDate) {
    
    this.enrollmentDate = enrollmentDate;
    return this;
  }

   /**
   * The date assigned by the Company to an account to avail rewards benefits
   * @return enrollmentDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2018-03-11", value = "The date assigned by the Company to an account to avail rewards benefits")

  public String getEnrollmentDate() {
    return enrollmentDate;
  }


  public void setEnrollmentDate(String enrollmentDate) {
    this.enrollmentDate = enrollmentDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Account account = (Account) o;
    return Objects.equals(this.accountIdType, account.accountIdType) &&
        Objects.equals(this.accountId, account.accountId) &&
        Objects.equals(this.status, account.status) &&
        Objects.equals(this.productCode, account.productCode) &&
        Objects.equals(this.programIdentifier, account.programIdentifier) &&
        Objects.equals(this.openDate, account.openDate) &&
        Objects.equals(this.enrollmentDate, account.enrollmentDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountIdType, accountId, status, productCode, programIdentifier, openDate, enrollmentDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Account {\n");
    sb.append("    accountIdType: ").append(toIndentedString(accountIdType)).append("\n");
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    productCode: ").append(toIndentedString(productCode)).append("\n");
    sb.append("    programIdentifier: ").append(toIndentedString(programIdentifier)).append("\n");
    sb.append("    openDate: ").append(toIndentedString(openDate)).append("\n");
    sb.append("    enrollmentDate: ").append(toIndentedString(enrollmentDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

