/*
 * User Account Management
 * API interface to enroll users and accounts
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Loyalty_Technology_Solutions_Scrum_Vulcans@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.developer.mastercard_loyalty_enrollment_client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * AccountSearchResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-02-11T17:56:47.857+05:30[Asia/Kolkata]")
public class AccountSearchResponse {
  public static final String SERIALIZED_NAME_COMPANY_ID = "companyId";
  @SerializedName(SERIALIZED_NAME_COMPANY_ID)
  private String companyId;

  public static final String SERIALIZED_NAME_USER_ID_TYPE = "userIdType";
  @SerializedName(SERIALIZED_NAME_USER_ID_TYPE)
  private String userIdType;

  public static final String SERIALIZED_NAME_USER_ID = "userId";
  @SerializedName(SERIALIZED_NAME_USER_ID)
  private String userId;

  public static final String SERIALIZED_NAME_ACCOUNT_ID_TYPE = "accountIdType";
  @SerializedName(SERIALIZED_NAME_ACCOUNT_ID_TYPE)
  private String accountIdType;

  public static final String SERIALIZED_NAME_ACCOUNT_ID = "accountId";
  @SerializedName(SERIALIZED_NAME_ACCOUNT_ID)
  private String accountId;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private String status;

  public static final String SERIALIZED_NAME_PRODUCT_CODE = "productCode";
  @SerializedName(SERIALIZED_NAME_PRODUCT_CODE)
  private String productCode;

  public static final String SERIALIZED_NAME_PROGRAM_IDENTIFIER = "programIdentifier";
  @SerializedName(SERIALIZED_NAME_PROGRAM_IDENTIFIER)
  private String programIdentifier;

  public static final String SERIALIZED_NAME_OPEN_DATE = "openDate";
  @SerializedName(SERIALIZED_NAME_OPEN_DATE)
  private String openDate;

  public static final String SERIALIZED_NAME_ENROLLMENT_DATE = "enrollmentDate";
  @SerializedName(SERIALIZED_NAME_ENROLLMENT_DATE)
  private String enrollmentDate;

  public static final String SERIALIZED_NAME_REFERENCE_ID = "referenceId";
  @SerializedName(SERIALIZED_NAME_REFERENCE_ID)
  private String referenceId;


  public AccountSearchResponse companyId(String companyId) {
    
    this.companyId = companyId;
    return this;
  }

   /**
   * The unique identifier of the company
   * @return companyId
  **/
  @ApiModelProperty(example = "611532", required = true, value = "The unique identifier of the company")

  public String getCompanyId() {
    return companyId;
  }


  public void setCompanyId(String companyId) {
    this.companyId = companyId;
  }


  public AccountSearchResponse userIdType(String userIdType) {
    
    this.userIdType = userIdType;
    return this;
  }

   /**
   * For Issuer, this value has to be CUSTOMER_NUMBER
   * @return userIdType
  **/
  @ApiModelProperty(example = "CUSTOMER_NUMBER", required = true, value = "For Issuer, this value has to be CUSTOMER_NUMBER")

  public String getUserIdType() {
    return userIdType;
  }


  public void setUserIdType(String userIdType) {
    this.userIdType = userIdType;
  }


  public AccountSearchResponse userId(String userId) {
    
    this.userId = userId;
    return this;
  }

   /**
   * The unique identifier assigned by the Company to the User
   * @return userId
  **/
  @ApiModelProperty(example = "C02333333325", required = true, value = "The unique identifier assigned by the Company to the User")

  public String getUserId() {
    return userId;
  }


  public void setUserId(String userId) {
    this.userId = userId;
  }


  public AccountSearchResponse accountIdType(String accountIdType) {
    
    this.accountIdType = accountIdType;
    return this;
  }

   /**
   * For real card number enrollment, AccountIdType has to be ACCOUNT_NUMBER
   * @return accountIdType
  **/
  @ApiModelProperty(example = "ACCOUNT_NUMBER", required = true, value = "For real card number enrollment, AccountIdType has to be ACCOUNT_NUMBER")

  public String getAccountIdType() {
    return accountIdType;
  }


  public void setAccountIdType(String accountIdType) {
    this.accountIdType = accountIdType;
  }


  public AccountSearchResponse accountId(String accountId) {
    
    this.accountId = accountId;
    return this;
  }

   /**
   * The unique identifier assigned by the Company to an account
   * @return accountId
  **/
  @ApiModelProperty(example = "5330333671236516", required = true, value = "The unique identifier assigned by the Company to an account")

  public String getAccountId() {
    return accountId;
  }


  public void setAccountId(String accountId) {
    this.accountId = accountId;
  }


  public AccountSearchResponse status(String status) {
    
    this.status = status;
    return this;
  }

   /**
   * Status for the user&#39;s account; Expected values are - NEW, GOOD_STANDING, REDEEM_ONLY, CANCELLED, ON_HOLD, INACTIVE
   * @return status
  **/
  @ApiModelProperty(example = "NEW", required = true, value = "Status for the user's account; Expected values are - NEW, GOOD_STANDING, REDEEM_ONLY, CANCELLED, ON_HOLD, INACTIVE")

  public String getStatus() {
    return status;
  }


  public void setStatus(String status) {
    this.status = status;
  }


  public AccountSearchResponse productCode(String productCode) {
    
    this.productCode = productCode;
    return this;
  }

   /**
   * Card product assigned by the Company
   * @return productCode
  **/
  @ApiModelProperty(example = "7274VCC", required = true, value = "Card product assigned by the Company")

  public String getProductCode() {
    return productCode;
  }


  public void setProductCode(String productCode) {
    this.productCode = productCode;
  }


  public AccountSearchResponse programIdentifier(String programIdentifier) {
    
    this.programIdentifier = programIdentifier;
    return this;
  }

   /**
   * Program unique identifier assigned by the Company
   * @return programIdentifier
  **/
  @ApiModelProperty(example = "ZXSzM", required = true, value = "Program unique identifier assigned by the Company")

  public String getProgramIdentifier() {
    return programIdentifier;
  }


  public void setProgramIdentifier(String programIdentifier) {
    this.programIdentifier = programIdentifier;
  }


  public AccountSearchResponse openDate(String openDate) {
    
    this.openDate = openDate;
    return this;
  }

   /**
   * The Date when account opened by the Company
   * @return openDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2015-01-01", value = "The Date when account opened by the Company")

  public String getOpenDate() {
    return openDate;
  }


  public void setOpenDate(String openDate) {
    this.openDate = openDate;
  }


  public AccountSearchResponse enrollmentDate(String enrollmentDate) {
    
    this.enrollmentDate = enrollmentDate;
    return this;
  }

   /**
   * The date assigned by the Company to an account to avail rewards benefits
   * @return enrollmentDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2018-03-11", value = "The date assigned by the Company to an account to avail rewards benefits")

  public String getEnrollmentDate() {
    return enrollmentDate;
  }


  public void setEnrollmentDate(String enrollmentDate) {
    this.enrollmentDate = enrollmentDate;
  }


  public AccountSearchResponse referenceId(String referenceId) {
    
    this.referenceId = referenceId;
    return this;
  }

   /**
   * A system generated unique identifier for the User&#39;s account
   * @return referenceId
  **/
  @ApiModelProperty(example = "d8753780-62d1-4775-9549-8ed92c48c290", required = true, value = "A system generated unique identifier for the User's account")

  public String getReferenceId() {
    return referenceId;
  }


  public void setReferenceId(String referenceId) {
    this.referenceId = referenceId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccountSearchResponse accountSearchResponse = (AccountSearchResponse) o;
    return Objects.equals(this.companyId, accountSearchResponse.companyId) &&
        Objects.equals(this.userIdType, accountSearchResponse.userIdType) &&
        Objects.equals(this.userId, accountSearchResponse.userId) &&
        Objects.equals(this.accountIdType, accountSearchResponse.accountIdType) &&
        Objects.equals(this.accountId, accountSearchResponse.accountId) &&
        Objects.equals(this.status, accountSearchResponse.status) &&
        Objects.equals(this.productCode, accountSearchResponse.productCode) &&
        Objects.equals(this.programIdentifier, accountSearchResponse.programIdentifier) &&
        Objects.equals(this.openDate, accountSearchResponse.openDate) &&
        Objects.equals(this.enrollmentDate, accountSearchResponse.enrollmentDate) &&
        Objects.equals(this.referenceId, accountSearchResponse.referenceId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(companyId, userIdType, userId, accountIdType, accountId, status, productCode, programIdentifier, openDate, enrollmentDate, referenceId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountSearchResponse {\n");
    sb.append("    companyId: ").append(toIndentedString(companyId)).append("\n");
    sb.append("    userIdType: ").append(toIndentedString(userIdType)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    accountIdType: ").append(toIndentedString(accountIdType)).append("\n");
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    productCode: ").append(toIndentedString(productCode)).append("\n");
    sb.append("    programIdentifier: ").append(toIndentedString(programIdentifier)).append("\n");
    sb.append("    openDate: ").append(toIndentedString(openDate)).append("\n");
    sb.append("    enrollmentDate: ").append(toIndentedString(enrollmentDate)).append("\n");
    sb.append("    referenceId: ").append(toIndentedString(referenceId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

