/*
 * User Account Management
 * API interface to enroll users and accounts
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Loyalty_Technology_Solutions_Scrum_Vulcans@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.developer.mastercard_loyalty_enrollment_client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * UserSearchRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-02-11T17:56:47.857+05:30[Asia/Kolkata]")
public class UserSearchRequest {
  public static final String SERIALIZED_NAME_COMPANY_ID = "companyId";
  @SerializedName(SERIALIZED_NAME_COMPANY_ID)
  private String companyId;

  public static final String SERIALIZED_NAME_USER_ID_TYPE = "userIdType";
  @SerializedName(SERIALIZED_NAME_USER_ID_TYPE)
  private String userIdType;

  public static final String SERIALIZED_NAME_USER_ID = "userId";
  @SerializedName(SERIALIZED_NAME_USER_ID)
  private String userId;


  public UserSearchRequest companyId(String companyId) {
    
    this.companyId = companyId;
    return this;
  }

   /**
   * The unique identifier of the company
   * @return companyId
  **/
  @ApiModelProperty(example = "611532", required = true, value = "The unique identifier of the company")

  public String getCompanyId() {
    return companyId;
  }


  public void setCompanyId(String companyId) {
    this.companyId = companyId;
  }


  public UserSearchRequest userIdType(String userIdType) {
    
    this.userIdType = userIdType;
    return this;
  }

   /**
   * For Issuer, this value has to be CUSTOMER_NUMBER
   * @return userIdType
  **/
  @ApiModelProperty(example = "CUSTOMER_NUMBER", required = true, value = "For Issuer, this value has to be CUSTOMER_NUMBER")

  public String getUserIdType() {
    return userIdType;
  }


  public void setUserIdType(String userIdType) {
    this.userIdType = userIdType;
  }


  public UserSearchRequest userId(String userId) {
    
    this.userId = userId;
    return this;
  }

   /**
   * The identifier assigned by the Company to the User
   * @return userId
  **/
  @ApiModelProperty(example = "C02333333325", required = true, value = "The identifier assigned by the Company to the User")

  public String getUserId() {
    return userId;
  }


  public void setUserId(String userId) {
    this.userId = userId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserSearchRequest userSearchRequest = (UserSearchRequest) o;
    return Objects.equals(this.companyId, userSearchRequest.companyId) &&
        Objects.equals(this.userIdType, userSearchRequest.userIdType) &&
        Objects.equals(this.userId, userSearchRequest.userId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(companyId, userIdType, userId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserSearchRequest {\n");
    sb.append("    companyId: ").append(toIndentedString(companyId)).append("\n");
    sb.append("    userIdType: ").append(toIndentedString(userIdType)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

