/*
 * User Account Management
 * API interface to enroll users and accounts
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Loyalty_Technology_Solutions_Scrum_Vulcans@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.developer.mastercard_loyalty_enrollment_client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * UserEnrollRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-02-11T17:56:47.857+05:30[Asia/Kolkata]")
public class UserEnrollRequest {
  public static final String SERIALIZED_NAME_COMPANY_ID = "companyId";
  @SerializedName(SERIALIZED_NAME_COMPANY_ID)
  private String companyId;

  public static final String SERIALIZED_NAME_USER_ID_TYPE = "userIdType";
  @SerializedName(SERIALIZED_NAME_USER_ID_TYPE)
  private String userIdType;

  public static final String SERIALIZED_NAME_USER_ID = "userId";
  @SerializedName(SERIALIZED_NAME_USER_ID)
  private String userId;

  public static final String SERIALIZED_NAME_FIRST_NAME = "firstName";
  @SerializedName(SERIALIZED_NAME_FIRST_NAME)
  private String firstName;

  public static final String SERIALIZED_NAME_LAST_NAME = "lastName";
  @SerializedName(SERIALIZED_NAME_LAST_NAME)
  private String lastName;

  public static final String SERIALIZED_NAME_MOTHER_MAIDEN_NAME = "motherMaidenName";
  @SerializedName(SERIALIZED_NAME_MOTHER_MAIDEN_NAME)
  private String motherMaidenName;

  public static final String SERIALIZED_NAME_GENDER = "gender";
  @SerializedName(SERIALIZED_NAME_GENDER)
  private String gender;

  public static final String SERIALIZED_NAME_BIRTH_DATE = "birthDate";
  @SerializedName(SERIALIZED_NAME_BIRTH_DATE)
  private String birthDate;

  public static final String SERIALIZED_NAME_NATIONAL_IDENTIFIER = "nationalIdentifier";
  @SerializedName(SERIALIZED_NAME_NATIONAL_IDENTIFIER)
  private String nationalIdentifier;

  public static final String SERIALIZED_NAME_BUSINESS_PHONE_NUMBER = "businessPhoneNumber";
  @SerializedName(SERIALIZED_NAME_BUSINESS_PHONE_NUMBER)
  private String businessPhoneNumber;

  public static final String SERIALIZED_NAME_MOBILE_PHONE_NUMBER = "mobilePhoneNumber";
  @SerializedName(SERIALIZED_NAME_MOBILE_PHONE_NUMBER)
  private String mobilePhoneNumber;

  public static final String SERIALIZED_NAME_HOME_PHONE_NUMBER = "homePhoneNumber";
  @SerializedName(SERIALIZED_NAME_HOME_PHONE_NUMBER)
  private String homePhoneNumber;

  public static final String SERIALIZED_NAME_EMAIL_ADDRESS = "emailAddress";
  @SerializedName(SERIALIZED_NAME_EMAIL_ADDRESS)
  private String emailAddress;

  public static final String SERIALIZED_NAME_VIP = "vip";
  @SerializedName(SERIALIZED_NAME_VIP)
  private Boolean vip;

  public static final String SERIALIZED_NAME_EMPLOYEE = "employee";
  @SerializedName(SERIALIZED_NAME_EMPLOYEE)
  private Boolean employee;

  public static final String SERIALIZED_NAME_GENERIC_IDENTIFICATION = "genericIdentification";
  @SerializedName(SERIALIZED_NAME_GENERIC_IDENTIFICATION)
  private String genericIdentification;

  public static final String SERIALIZED_NAME_GENERIC_IDENTIFICATION_DESCRIPTION = "genericIdentificationDescription";
  @SerializedName(SERIALIZED_NAME_GENERIC_IDENTIFICATION_DESCRIPTION)
  private String genericIdentificationDescription;

  public static final String SERIALIZED_NAME_ADDRESS = "address";
  @SerializedName(SERIALIZED_NAME_ADDRESS)
  private UserAddress address;

  public static final String SERIALIZED_NAME_ACCOUNT = "account";
  @SerializedName(SERIALIZED_NAME_ACCOUNT)
  private Account account;


  public UserEnrollRequest companyId(String companyId) {
    
    this.companyId = companyId;
    return this;
  }

   /**
   * The unique identifier of the company
   * @return companyId
  **/
  @ApiModelProperty(example = "611532", required = true, value = "The unique identifier of the company")

  public String getCompanyId() {
    return companyId;
  }


  public void setCompanyId(String companyId) {
    this.companyId = companyId;
  }


  public UserEnrollRequest userIdType(String userIdType) {
    
    this.userIdType = userIdType;
    return this;
  }

   /**
   * For Issuer, this value has to be CUSTOMER_NUMBER
   * @return userIdType
  **/
  @ApiModelProperty(example = "CUSTOMER_NUMBER", required = true, value = "For Issuer, this value has to be CUSTOMER_NUMBER")

  public String getUserIdType() {
    return userIdType;
  }


  public void setUserIdType(String userIdType) {
    this.userIdType = userIdType;
  }


  public UserEnrollRequest userId(String userId) {
    
    this.userId = userId;
    return this;
  }

   /**
   * The unique identifier assigned by the Company to the User
   * @return userId
  **/
  @ApiModelProperty(example = "C02333333325", required = true, value = "The unique identifier assigned by the Company to the User")

  public String getUserId() {
    return userId;
  }


  public void setUserId(String userId) {
    this.userId = userId;
  }


  public UserEnrollRequest firstName(String firstName) {
    
    this.firstName = firstName;
    return this;
  }

   /**
   * User&#39;s first name
   * @return firstName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "John", value = "User's first name")

  public String getFirstName() {
    return firstName;
  }


  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }


  public UserEnrollRequest lastName(String lastName) {
    
    this.lastName = lastName;
    return this;
  }

   /**
   * User&#39;s last name
   * @return lastName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Smith", value = "User's last name")

  public String getLastName() {
    return lastName;
  }


  public void setLastName(String lastName) {
    this.lastName = lastName;
  }


  public UserEnrollRequest motherMaidenName(String motherMaidenName) {
    
    this.motherMaidenName = motherMaidenName;
    return this;
  }

   /**
   * User&#39;s mother maiden name
   * @return motherMaidenName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Smith", value = "User's mother maiden name")

  public String getMotherMaidenName() {
    return motherMaidenName;
  }


  public void setMotherMaidenName(String motherMaidenName) {
    this.motherMaidenName = motherMaidenName;
  }


  public UserEnrollRequest gender(String gender) {
    
    this.gender = gender;
    return this;
  }

   /**
   * The ISO code used to determine the gender of the User; Expected values- 0(not known-default), 1(male), 2(female), 9(not applicable)
   * @return gender
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "The ISO code used to determine the gender of the User; Expected values- 0(not known-default), 1(male), 2(female), 9(not applicable)")

  public String getGender() {
    return gender;
  }


  public void setGender(String gender) {
    this.gender = gender;
  }


  public UserEnrollRequest birthDate(String birthDate) {
    
    this.birthDate = birthDate;
    return this;
  }

   /**
   * User&#39;s date of birth
   * @return birthDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1975-03-11", value = "User's date of birth")

  public String getBirthDate() {
    return birthDate;
  }


  public void setBirthDate(String birthDate) {
    this.birthDate = birthDate;
  }


  public UserEnrollRequest nationalIdentifier(String nationalIdentifier) {
    
    this.nationalIdentifier = nationalIdentifier;
    return this;
  }

   /**
   * National Identifier of the User
   * @return nationalIdentifier
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "324-56-7574", value = "National Identifier of the User")

  public String getNationalIdentifier() {
    return nationalIdentifier;
  }


  public void setNationalIdentifier(String nationalIdentifier) {
    this.nationalIdentifier = nationalIdentifier;
  }


  public UserEnrollRequest businessPhoneNumber(String businessPhoneNumber) {
    
    this.businessPhoneNumber = businessPhoneNumber;
    return this;
  }

   /**
   * Valid business phone number used by the User
   * @return businessPhoneNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "+1(0)1234567890", value = "Valid business phone number used by the User")

  public String getBusinessPhoneNumber() {
    return businessPhoneNumber;
  }


  public void setBusinessPhoneNumber(String businessPhoneNumber) {
    this.businessPhoneNumber = businessPhoneNumber;
  }


  public UserEnrollRequest mobilePhoneNumber(String mobilePhoneNumber) {
    
    this.mobilePhoneNumber = mobilePhoneNumber;
    return this;
  }

   /**
   * Valid mobile phone number used by the User
   * @return mobilePhoneNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "+1(0)1234567891", value = "Valid mobile phone number used by the User")

  public String getMobilePhoneNumber() {
    return mobilePhoneNumber;
  }


  public void setMobilePhoneNumber(String mobilePhoneNumber) {
    this.mobilePhoneNumber = mobilePhoneNumber;
  }


  public UserEnrollRequest homePhoneNumber(String homePhoneNumber) {
    
    this.homePhoneNumber = homePhoneNumber;
    return this;
  }

   /**
   * Valid home phone number used by the User
   * @return homePhoneNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "+1(0)1234567892", value = "Valid home phone number used by the User")

  public String getHomePhoneNumber() {
    return homePhoneNumber;
  }


  public void setHomePhoneNumber(String homePhoneNumber) {
    this.homePhoneNumber = homePhoneNumber;
  }


  public UserEnrollRequest emailAddress(String emailAddress) {
    
    this.emailAddress = emailAddress;
    return this;
  }

   /**
   * Valid email address used by the User
   * @return emailAddress
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "john.smith@mastercard.com", value = "Valid email address used by the User")

  public String getEmailAddress() {
    return emailAddress;
  }


  public void setEmailAddress(String emailAddress) {
    this.emailAddress = emailAddress;
  }


  public UserEnrollRequest vip(Boolean vip) {
    
    this.vip = vip;
    return this;
  }

   /**
   * Allows the user to holds VIP status, default value is false
   * @return vip
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "true", value = "Allows the user to holds VIP status, default value is false")

  public Boolean getVip() {
    return vip;
  }


  public void setVip(Boolean vip) {
    this.vip = vip;
  }


  public UserEnrollRequest employee(Boolean employee) {
    
    this.employee = employee;
    return this;
  }

   /**
   * Allows the user to holds EMPLOYEE status, default value is false
   * @return employee
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "false", value = "Allows the user to holds EMPLOYEE status, default value is false")

  public Boolean getEmployee() {
    return employee;
  }


  public void setEmployee(Boolean employee) {
    this.employee = employee;
  }


  public UserEnrollRequest genericIdentification(String genericIdentification) {
    
    this.genericIdentification = genericIdentification;
    return this;
  }

   /**
   * Answer to the user’s verification question
   * @return genericIdentification
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Duster", value = "Answer to the user’s verification question")

  public String getGenericIdentification() {
    return genericIdentification;
  }


  public void setGenericIdentification(String genericIdentification) {
    this.genericIdentification = genericIdentification;
  }


  public UserEnrollRequest genericIdentificationDescription(String genericIdentificationDescription) {
    
    this.genericIdentificationDescription = genericIdentificationDescription;
    return this;
  }

   /**
   * The user’s custom verification question
   * @return genericIdentificationDescription
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Pet's name", value = "The user’s custom verification question")

  public String getGenericIdentificationDescription() {
    return genericIdentificationDescription;
  }


  public void setGenericIdentificationDescription(String genericIdentificationDescription) {
    this.genericIdentificationDescription = genericIdentificationDescription;
  }


  public UserEnrollRequest address(UserAddress address) {
    
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public UserAddress getAddress() {
    return address;
  }


  public void setAddress(UserAddress address) {
    this.address = address;
  }


  public UserEnrollRequest account(Account account) {
    
    this.account = account;
    return this;
  }

   /**
   * Get account
   * @return account
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Account getAccount() {
    return account;
  }


  public void setAccount(Account account) {
    this.account = account;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserEnrollRequest userEnrollRequest = (UserEnrollRequest) o;
    return Objects.equals(this.companyId, userEnrollRequest.companyId) &&
        Objects.equals(this.userIdType, userEnrollRequest.userIdType) &&
        Objects.equals(this.userId, userEnrollRequest.userId) &&
        Objects.equals(this.firstName, userEnrollRequest.firstName) &&
        Objects.equals(this.lastName, userEnrollRequest.lastName) &&
        Objects.equals(this.motherMaidenName, userEnrollRequest.motherMaidenName) &&
        Objects.equals(this.gender, userEnrollRequest.gender) &&
        Objects.equals(this.birthDate, userEnrollRequest.birthDate) &&
        Objects.equals(this.nationalIdentifier, userEnrollRequest.nationalIdentifier) &&
        Objects.equals(this.businessPhoneNumber, userEnrollRequest.businessPhoneNumber) &&
        Objects.equals(this.mobilePhoneNumber, userEnrollRequest.mobilePhoneNumber) &&
        Objects.equals(this.homePhoneNumber, userEnrollRequest.homePhoneNumber) &&
        Objects.equals(this.emailAddress, userEnrollRequest.emailAddress) &&
        Objects.equals(this.vip, userEnrollRequest.vip) &&
        Objects.equals(this.employee, userEnrollRequest.employee) &&
        Objects.equals(this.genericIdentification, userEnrollRequest.genericIdentification) &&
        Objects.equals(this.genericIdentificationDescription, userEnrollRequest.genericIdentificationDescription) &&
        Objects.equals(this.address, userEnrollRequest.address) &&
        Objects.equals(this.account, userEnrollRequest.account);
  }

  @Override
  public int hashCode() {
    return Objects.hash(companyId, userIdType, userId, firstName, lastName, motherMaidenName, gender, birthDate, nationalIdentifier, businessPhoneNumber, mobilePhoneNumber, homePhoneNumber, emailAddress, vip, employee, genericIdentification, genericIdentificationDescription, address, account);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserEnrollRequest {\n");
    sb.append("    companyId: ").append(toIndentedString(companyId)).append("\n");
    sb.append("    userIdType: ").append(toIndentedString(userIdType)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    motherMaidenName: ").append(toIndentedString(motherMaidenName)).append("\n");
    sb.append("    gender: ").append(toIndentedString(gender)).append("\n");
    sb.append("    birthDate: ").append(toIndentedString(birthDate)).append("\n");
    sb.append("    nationalIdentifier: ").append(toIndentedString(nationalIdentifier)).append("\n");
    sb.append("    businessPhoneNumber: ").append(toIndentedString(businessPhoneNumber)).append("\n");
    sb.append("    mobilePhoneNumber: ").append(toIndentedString(mobilePhoneNumber)).append("\n");
    sb.append("    homePhoneNumber: ").append(toIndentedString(homePhoneNumber)).append("\n");
    sb.append("    emailAddress: ").append(toIndentedString(emailAddress)).append("\n");
    sb.append("    vip: ").append(toIndentedString(vip)).append("\n");
    sb.append("    employee: ").append(toIndentedString(employee)).append("\n");
    sb.append("    genericIdentification: ").append(toIndentedString(genericIdentification)).append("\n");
    sb.append("    genericIdentificationDescription: ").append(toIndentedString(genericIdentificationDescription)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    account: ").append(toIndentedString(account)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

