/*
 * User Account Management
 * API interface to enroll users and accounts
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Loyalty_Technology_Solutions_Scrum_Vulcans@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.developer.mastercard_loyalty_enrollment_client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for AccountEnrollRequest
 */
public class AccountEnrollRequestTest {
    private final AccountEnrollRequest model = new AccountEnrollRequest();

    /**
     * Model tests for AccountEnrollRequest
     */
    @Test
    public void testAccountEnrollRequest() {
        // TODO: test AccountEnrollRequest
    }

    /**
     * Test the property 'companyId'
     */
    @Test
    public void companyIdTest() {
        // TODO: test companyId
    }

    /**
     * Test the property 'userIdType'
     */
    @Test
    public void userIdTypeTest() {
        // TODO: test userIdType
    }

    /**
     * Test the property 'userId'
     */
    @Test
    public void userIdTest() {
        // TODO: test userId
    }

    /**
     * Test the property 'accountIdType'
     */
    @Test
    public void accountIdTypeTest() {
        // TODO: test accountIdType
    }

    /**
     * Test the property 'accountId'
     */
    @Test
    public void accountIdTest() {
        // TODO: test accountId
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'productCode'
     */
    @Test
    public void productCodeTest() {
        // TODO: test productCode
    }

    /**
     * Test the property 'programIdentifier'
     */
    @Test
    public void programIdentifierTest() {
        // TODO: test programIdentifier
    }

    /**
     * Test the property 'openDate'
     */
    @Test
    public void openDateTest() {
        // TODO: test openDate
    }

    /**
     * Test the property 'enrollmentDate'
     */
    @Test
    public void enrollmentDateTest() {
        // TODO: test enrollmentDate
    }

}
