/*
 * User Account Management
 * API interface to enroll users and accounts
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Loyalty_Technology_Solutions_Scrum_Vulcans@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.developer.mastercard_loyalty_enrollment_client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.mastercard.developer.mastercard_loyalty_enrollment_client.model.UserAddress;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for UserSearchResponse
 */
public class UserSearchResponseTest {
    private final UserSearchResponse model = new UserSearchResponse();

    /**
     * Model tests for UserSearchResponse
     */
    @Test
    public void testUserSearchResponse() {
        // TODO: test UserSearchResponse
    }

    /**
     * Test the property 'companyId'
     */
    @Test
    public void companyIdTest() {
        // TODO: test companyId
    }

    /**
     * Test the property 'userIdType'
     */
    @Test
    public void userIdTypeTest() {
        // TODO: test userIdType
    }

    /**
     * Test the property 'userId'
     */
    @Test
    public void userIdTest() {
        // TODO: test userId
    }

    /**
     * Test the property 'firstName'
     */
    @Test
    public void firstNameTest() {
        // TODO: test firstName
    }

    /**
     * Test the property 'lastName'
     */
    @Test
    public void lastNameTest() {
        // TODO: test lastName
    }

    /**
     * Test the property 'motherMaidenName'
     */
    @Test
    public void motherMaidenNameTest() {
        // TODO: test motherMaidenName
    }

    /**
     * Test the property 'gender'
     */
    @Test
    public void genderTest() {
        // TODO: test gender
    }

    /**
     * Test the property 'birthDate'
     */
    @Test
    public void birthDateTest() {
        // TODO: test birthDate
    }

    /**
     * Test the property 'nationalIdentifier'
     */
    @Test
    public void nationalIdentifierTest() {
        // TODO: test nationalIdentifier
    }

    /**
     * Test the property 'businessPhoneNumber'
     */
    @Test
    public void businessPhoneNumberTest() {
        // TODO: test businessPhoneNumber
    }

    /**
     * Test the property 'mobilePhoneNumber'
     */
    @Test
    public void mobilePhoneNumberTest() {
        // TODO: test mobilePhoneNumber
    }

    /**
     * Test the property 'homePhoneNumber'
     */
    @Test
    public void homePhoneNumberTest() {
        // TODO: test homePhoneNumber
    }

    /**
     * Test the property 'emailAddress'
     */
    @Test
    public void emailAddressTest() {
        // TODO: test emailAddress
    }

    /**
     * Test the property 'vip'
     */
    @Test
    public void vipTest() {
        // TODO: test vip
    }

    /**
     * Test the property 'employee'
     */
    @Test
    public void employeeTest() {
        // TODO: test employee
    }

    /**
     * Test the property 'genericIdentification'
     */
    @Test
    public void genericIdentificationTest() {
        // TODO: test genericIdentification
    }

    /**
     * Test the property 'genericIdentificationDescription'
     */
    @Test
    public void genericIdentificationDescriptionTest() {
        // TODO: test genericIdentificationDescription
    }

    /**
     * Test the property 'address'
     */
    @Test
    public void addressTest() {
        // TODO: test address
    }

    /**
     * Test the property 'referenceId'
     */
    @Test
    public void referenceIdTest() {
        // TODO: test referenceId
    }

}
